---
- name: Check if rbenv is already installed
  become: yes
  become_user: "{{ machine_user }}"
  stat:
    path: "~/.rbenv"
  register: rbenv_stat

# Script from https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer
- name: Install rbenv
  become: yes
  become_user: "{{ machine_user }}"
  script: "files/rbenv-installer"
  when: not rbenv_stat.stat.exists
