---
- name: Check if frtizing IDE is installed
  stat:
    path: "/opt/fritzing-{{ fritzing_ide.version }}"
  register: fritzing

- name: Download and install fritzing IDE
  block:
    - name: Download fritzing IDE
      get_url:
        url: "{{ fritzing_ide.url }}"
        dest: "/tmp/fritzing-{{ fritzing_ide.version }}.tar.bz2"
        checksum: "{{ fritzing_ide.checksum }}"
        mode: '0777'

    - name: Ensure fritzing dir exists
      file:
        path: "/opt/fritzing-{{ fritzing_ide.version }}"
        state: directory
        mode: '0755'

    - name: Unarchive fritzing IDE
      unarchive:
        src: "/tmp/fritzing-{{ fritzing_ide.version }}.tar.bz2"
        dest: "/opt/fritzing-{{ fritzing_ide.version }}/"
        remote_src: yes
        extra_opts: "--strip-components=1"
  when: not fritzing.stat.exists

- name: Fritzing IDE link
  file:
    src: "/opt/fritzing-{{ fritzing_ide.version }}"
    dest: "/opt/fritzing"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: link
