---
apt_packages:
- "git"
- "stubby"
- "uuid"
- "libgstreamer1.0-0"
- "gstreamer1.0-plugins-base"
- "gstreamer1.0-plugins-good"
- "gstreamer1.0-plugins-bad"
- "gstreamer1.0-plugins-ugly"
- "gstreamer1.0-gtk3"
- "pavucontrol"
- "firejail"
- "nfs-common"
- "xz-utils"
- "sl"
- "rpm2cpio"
- "libclang-dev"
- "llvm-dev"
- "clang"
- "musl-tools"
- "libssl-dev"
- "openssl"
- "anki"
- "thunderbird"
- "gcc"
- "bison"
- "libqt5printsupport5"
- "libqt5xml5"
- "libqt5sql5"
- "libqt5serialport5"
- "libqt5sql5-sqlite"
# - "libc6:i386"
# - "libncurses5:i386"
# - "libstdc++6:i386"
- "lib32z1"
# - "libbz2-1.0:i386"
- "qemu-kvm"
- "libpq-dev"
- "libx11-xcb1"
- "libxcb-dri2-0"
- "libxcb-dri3-0"
- "libxcb-glx0"
- "libxcb-present0"
- "libxcb-sync1"
- "libxcb-xfixes0"
- "wireshark"
- "net-tools"
- "gddrescue"
- "sleuthkit"
- "testdisk"
- "python-setuptools"
- "python3-pip"
- "android-sdk-platform-tools-common"
- "adb"
- "sqlite3"
- "libarchive-tools"
- "pkg-config"
- "libasound2-dev"
- "cmake"
- "build-essential"
- "libfreetype6-dev"
- "libexpat1-dev"
- "libxcb-composite0-dev"
- "libx11-dev"
- "libfontconfig1-dev"
- "libgtk-3-dev"
- "gcc-arm-none-eabi"
- "scdaemon"
- "mingw-w64"
- "linux-tools-generic"
- "mdadm"
- "cifs-utils"
