---
rpm_packages:
- pass
- gimp
- wget
- tmux
- rawtherapee
- wl-clipboard
- make
- colordiff
- gcc
- gdb
- gimp
- nload
- git
- git-crypt
- git-lfs
- git-secrets
- hplip
- hplip-gui
- simple-scan
- thunderbird
- libffi-devel
- ncurses-libs
- bzip2-devel
- xz-devel
- readline-devel
- sqlite-devel
- tk-devel
- jq
- tree
- pwgen
- diskonaut
- ffmpeg
- pipx
- zstd
- webkit2gtk4.0
- libOSMesa
- ack
- cmake
- asciinema
- procs
- iftop
- htop
- chafa
- dosbox-staging
- hexyl
- dmg2img
- ripgrep
- tig
- dia
- lolcat
- most
- lynx
- potrace
- valgrind
- socat
- mc
- bat
- clang-tools-extra
- unrar
- sshuttle
- graphviz
- inkscape
- sshpass
- steam
- python3-pip
- git-delta
- yq
- alacritty
- calibre
- hstr
- restic
- wol

global_python_packages:
- uv
