[tools]
awscli = "latest"
go = "latest"
just = "latest"
k9s = "latest"
krew = "latest"
kustomize = "latest"
stern = "latest"
kubectl = "latest"
node = "latest"
uv = "latest"
gemini-cli = "latest"
minikube = "latest"

[settings]
lockfile = true
experimental = true
disable_backends = ["asdf"]
