---
- hosts: localhost
  gather_facts: false
  become: true
  roles:
    - pre

- hosts: localhost
  become: true
  roles:
    - system
    - gpg
    - python
    - udev
    - virtualbox
    - keybase
    - docker
    - arduino_ide
    - fritzing_ide
    - eagle_ide
    - flutter
    - android_studio
    - gvm
    - nvm
    - r
    - rust
