---
- hosts: localhost
  gather_facts: False
  become: yes
  roles:
    - pre

- hosts: localhost
  become: yes
  vars:
    machine_user: "fishi0x01"
  roles:
    - solokey
    - virtualbox
    - keybase
    - docker
    - arduino-ide
    - fritzing-ide
    - eagle-ide
    - flutter
    - android-studio
    - gvm
    - nvm
    - r

