---
- name: Check if GVM is already installed
  become: yes
  become_user: "{{ machine_user }}"
  stat:
    path: "~/.gvm"
  register: gvm_stat

# https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
- name: Install GVM
  become: yes
  become_user: "{{ machine_user }}"
  script: "files/gvm-installer"
  when: not gvm_stat.stat.exists

- name: Install go1.4 for compilation of go1.5+
  become: yes
  become_user: "{{ machine_user }}"
  shell: "gvm install go1.4 -B && gvm use go1.4"
  when: not gvm_stat.stat.exists
